spring.application.name=splitify
server.port=8080

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/splitify
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# JWT
app.jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
app.jwt.expiration-ms=86400000

# Gemini API
app.gemini.api-key=${GEMINI_API_KEY}
app.gemini.base-url=https://generativelanguage.googleapis.com
app.gemini.model=gemini-2.5-flash

# Multipart
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# CORS
app.cors.allowed-origins=http://localhost:8081,http://localhost:3000,exp://localhost:8081,exp://192.168.0.18:8081,http://192.168.0.18:8081